sudo: false

dist: trusty

language:
  - go

go:
  - "1.11"
  - "1.12"

git:
  depth: 1

install: true

script:
  # Verify that all source files are correctly formatted.
  - find . -name "*.go" | grep -v vendor/ | xargs gofmt -d -e -l
  
  - go get gotest.tools/gotestsum
  - go clean -i
  - gotestsum --format=standard-quiet --junitfile=junit_result.xml -- -v -race -count=1  -coverprofile=coverage.txt -covermode=atomic ./...

# TODO: Set up coverage.
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
